#!/usr/bin/env python3
"""Rebuild the bundled icon font from the icons the app actually uses.

The app used to pull Tabler's full webfont from jsdelivr, pinned to @latest:
203KB of CSS covering 4,962 icons and a 778KB font, fetched over the network
before a single icon could render — and liable to change without warning.

This subsets both down to the ~89 icons that appear in index.html.

RUN THIS AFTER ADDING A NEW ICON. If an icon is missing at runtime it will
render as a blank box, because its glyph was not in the subset.

    python3 scripts/build-icons.py
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, 'index.html')
SRC_CSS = os.path.join(ROOT, 'vendor', 'tabler-icons.min.css')
SRC_FONT = os.path.join(ROOT, 'vendor', 'fonts', 'tabler-icons.woff2')
OUT_CSS = os.path.join(ROOT, 'vendor', 'tabler-icons.subset.css')
OUT_FONT = os.path.join(ROOT, 'vendor', 'fonts', 'tabler-icons.subset.woff2')


def main():
    html = open(HTML, encoding='utf-8').read()
    css = open(SRC_CSS, encoding='utf-8').read()

    used = sorted(set(re.findall(r'\bti-([a-z0-9-]+)\b', html)))
    mapping = dict(re.findall(r'\.ti-([a-z0-9-]+):before\{content:"\\([0-9a-fA-F]+)"\}', css))
    found = {u: mapping[u] for u in used if u in mapping}
    missing = [u for u in used if u not in mapping]

    if missing:
        print(f"  ! {len(missing)} icon name(s) not in the Tabler set: {', '.join(missing[:8])}")

    # Subset the font to just those glyphs.
    from fontTools import subset
    subset.main([
        SRC_FONT,
        '--unicodes=' + ','.join('U+' + c.upper() for c in found.values()),
        '--flavor=woff2', '--output-file=' + OUT_FONT,
        '--no-hinting', '--desubroutinize',
        '--layout-features=', '--name-IDs=', '--notdef-outline',
    ])

    # Rebuild the stylesheet with only what is needed.
    rules = '\n'.join(f'.ti-{name}:before{{content:"\\{code}"}}'
                      for name, code in sorted(found.items()))
    out = f"""/* Generated by scripts/build-icons.py — do not edit by hand.
   Tabler Icons, subset to the {len(found)} icons this app uses.
   Re-run the script after adding a new icon or it will render as a blank box. */
@font-face {{
  font-family: 'tabler-icons';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url('fonts/tabler-icons.subset.woff2') format('woff2');
}}
.ti {{
  font-family: 'tabler-icons' !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}}
{rules}
"""
    open(OUT_CSS, 'w', encoding='utf-8').write(out)

    print(f"  icons used : {len(found)}")
    print(f"  css        : {os.path.getsize(SRC_CSS):>9,} → {os.path.getsize(OUT_CSS):>7,} bytes")
    print(f"  font       : {os.path.getsize(SRC_FONT):>9,} → {os.path.getsize(OUT_FONT):>7,} bytes")


if __name__ == '__main__':
    main()
