#!/usr/bin/env python3
"""Bundle the app's typefaces instead of fetching them from Google Fonts.

The stylesheet was loaded from fonts.googleapis.com, which then pulled woff2
files from fonts.gstatic.com — two network hops before any text could render in
the right face, on every cold start.

Keeps the latin and latin-ext subsets. Vietnamese is dropped (no Vietnamese in
the app), and Devanagari/Arabic were never in these families to begin with, so
Hindi and Arabic already fall back to the system font.

    python3 scripts/build-fonts.py
"""
import os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, 'vendor', 'fonts')
OUT_CSS = os.path.join(ROOT, 'vendor', 'fonts.css')
KEEP = {'latin', 'latin-ext'}

URL = ('https://fonts.googleapis.com/css2'
       '?family=DM+Sans:wght@400;500;600;700;800'
       '&family=Bricolage+Grotesque:wght@400;500;600;700;800&display=swap')
UA = ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0 Safari/537.36')


def fetch(url, binary=False):
    """Shell out to curl — this machine's Python has no CA bundle, so urllib
    fails TLS verification on every request."""
    out = subprocess.run(['curl', '-sL', '-A', UA, url, '--max-time', '60'],
                         capture_output=True, check=True).stdout
    return out if binary else out.decode('utf-8')


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    css = fetch(URL)
    blocks = re.findall(r'/\*\s*([a-z0-9-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)

    # Google serves ONE variable font per family+subset and points every weight
    # at it, so downloading per-weight stored the same bytes five times over.
    # Dedupe by content hash and let all weights share a single file.
    import hashlib
    out, skipped, total, seen = [], 0, 0, {}
    for subset_name, block in blocks:
        if subset_name not in KEEP:
            skipped += 1
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        src = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)

        data = fetch(src, binary=True)
        digest = hashlib.md5(data).hexdigest()[:8]
        if digest not in seen:
            name = f"{fam.replace(' ', '')}-{subset_name}-{digest}.woff2"
            open(os.path.join(OUT_DIR, name), 'wb').write(data)
            seen[digest] = name
            total += len(data)
        out.append(re.sub(r'url\(https://[^)]+\.woff2\)',
                          f"url('fonts/{seen[digest]}')", block))
    kept = len(seen)

    header = (f"/* Generated by scripts/build-fonts.py — do not edit by hand.\n"
              f"   {kept} unique font file(s) shared across {len(out)} @font-face rules.\n"
              f"   Subsets kept: {sorted(KEEP)}; {skipped} others skipped.\n"
              f"   Bundled so text renders without waiting on Google's servers. */\n")
    open(OUT_CSS, 'w', encoding='utf-8').write(header + '\n'.join(out) + '\n')
    print(f"  bundled : {kept} unique file(s) for {len(out)} rules, {total:,} bytes")
    print(f"  skipped : {skipped} (other unicode subsets)")
    print(f"  css     : {os.path.getsize(OUT_CSS):,} bytes → vendor/fonts.css")


if __name__ == '__main__':
    main()
